// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/consistent_hash.proto

package consistent_hash

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultCode int32

const (
	ResultCode_SUCCESS       ResultCode = 0
	ResultCode_KEY_NOT_EXIST ResultCode = 1
)

// Enum value maps for ResultCode.
var (
	ResultCode_name = map[int32]string{
		0: "SUCCESS",
		1: "KEY_NOT_EXIST",
	}
	ResultCode_value = map[string]int32{
		"SUCCESS":       0,
		"KEY_NOT_EXIST": 1,
	}
)

func (x ResultCode) Enum() *ResultCode {
	p := new(ResultCode)
	*p = x
	return p
}

func (x ResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_consistent_hash_proto_enumTypes[0].Descriptor()
}

func (ResultCode) Type() protoreflect.EnumType {
	return &file_proto_consistent_hash_proto_enumTypes[0]
}

func (x ResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultCode.Descriptor instead.
func (ResultCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{0}
}

type GetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_proto_consistent_hash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{0}
}

func (x *GetValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ResultCode    ResultCode             `protobuf:"varint,2,opt,name=result_code,json=resultCode,proto3,enum=consistent_hash.ResultCode" json:"result_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	mi := &file_proto_consistent_hash_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{1}
}

func (x *GetValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetValueResponse) GetResultCode() ResultCode {
	if x != nil {
		return x.ResultCode
	}
	return ResultCode_SUCCESS
}

type SetKVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKVRequest) Reset() {
	*x = SetKVRequest{}
	mi := &file_proto_consistent_hash_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKVRequest) ProtoMessage() {}

func (x *SetKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKVRequest.ProtoReflect.Descriptor instead.
func (*SetKVRequest) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{2}
}

func (x *SetKVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetKVRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetKVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    ResultCode             `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3,enum=consistent_hash.ResultCode" json:"result_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKVResponse) Reset() {
	*x = SetKVResponse{}
	mi := &file_proto_consistent_hash_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKVResponse) ProtoMessage() {}

func (x *SetKVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKVResponse.ProtoReflect.Descriptor instead.
func (*SetKVResponse) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{3}
}

func (x *SetKVResponse) GetResultCode() ResultCode {
	if x != nil {
		return x.ResultCode
	}
	return ResultCode_SUCCESS
}

type DeleteKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyRequest) Reset() {
	*x = DeleteKeyRequest{}
	mi := &file_proto_consistent_hash_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRequest) ProtoMessage() {}

func (x *DeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    ResultCode             `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3,enum=consistent_hash.ResultCode" json:"result_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyResponse) Reset() {
	*x = DeleteKeyResponse{}
	mi := &file_proto_consistent_hash_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResponse) ProtoMessage() {}

func (x *DeleteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteKeyResponse) GetResultCode() ResultCode {
	if x != nil {
		return x.ResultCode
	}
	return ResultCode_SUCCESS
}

type ServiceRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerId          string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	HearbeatTimestamp uint64                 `protobuf:"varint,3,opt,name=hearbeat_timestamp,json=hearbeatTimestamp,proto3" json:"hearbeat_timestamp,omitempty"`
	Vnode             []string               `protobuf:"bytes,4,rep,name=vnode,proto3" json:"vnode,omitempty"`
	IsSlaveOf         string                 `protobuf:"bytes,5,opt,name=is_slave_of,json=isSlaveOf,proto3" json:"is_slave_of,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServiceRecord) Reset() {
	*x = ServiceRecord{}
	mi := &file_proto_consistent_hash_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRecord) ProtoMessage() {}

func (x *ServiceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRecord.ProtoReflect.Descriptor instead.
func (*ServiceRecord) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceRecord) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServiceRecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServiceRecord) GetHearbeatTimestamp() uint64 {
	if x != nil {
		return x.HearbeatTimestamp
	}
	return 0
}

func (x *ServiceRecord) GetVnode() []string {
	if x != nil {
		return x.Vnode
	}
	return nil
}

func (x *ServiceRecord) GetIsSlaveOf() string {
	if x != nil {
		return x.IsSlaveOf
	}
	return ""
}

type Gossip struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status of orther server
	ServiceRecord []*ServiceRecord `protobuf:"bytes,1,rep,name=service_record,json=serviceRecord,proto3" json:"service_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gossip) Reset() {
	*x = Gossip{}
	mi := &file_proto_consistent_hash_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gossip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gossip) ProtoMessage() {}

func (x *Gossip) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gossip.ProtoReflect.Descriptor instead.
func (*Gossip) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{7}
}

func (x *Gossip) GetServiceRecord() []*ServiceRecord {
	if x != nil {
		return x.ServiceRecord
	}
	return nil
}

type RedirectGossipMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gossip        *Gossip                `protobuf:"bytes,1,opt,name=gossip,proto3" json:"gossip,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectGossipMessageRequest) Reset() {
	*x = RedirectGossipMessageRequest{}
	mi := &file_proto_consistent_hash_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectGossipMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectGossipMessageRequest) ProtoMessage() {}

func (x *RedirectGossipMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectGossipMessageRequest.ProtoReflect.Descriptor instead.
func (*RedirectGossipMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{8}
}

func (x *RedirectGossipMessageRequest) GetGossip() *Gossip {
	if x != nil {
		return x.Gossip
	}
	return nil
}

func (x *RedirectGossipMessageRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type RedirectGossipMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    ResultCode             `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3,enum=consistent_hash.ResultCode" json:"result_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectGossipMessageResponse) Reset() {
	*x = RedirectGossipMessageResponse{}
	mi := &file_proto_consistent_hash_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectGossipMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectGossipMessageResponse) ProtoMessage() {}

func (x *RedirectGossipMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectGossipMessageResponse.ProtoReflect.Descriptor instead.
func (*RedirectGossipMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{9}
}

func (x *RedirectGossipMessageResponse) GetResultCode() ResultCode {
	if x != nil {
		return x.ResultCode
	}
	return ResultCode_SUCCESS
}

type RedirectCloneKeyMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectCloneKeyMessageRequest) Reset() {
	*x = RedirectCloneKeyMessageRequest{}
	mi := &file_proto_consistent_hash_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectCloneKeyMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectCloneKeyMessageRequest) ProtoMessage() {}

func (x *RedirectCloneKeyMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectCloneKeyMessageRequest.ProtoReflect.Descriptor instead.
func (*RedirectCloneKeyMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{10}
}

func (x *RedirectCloneKeyMessageRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RedirectCloneKeyMessageRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RedirectCloneKeyMessageRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type RedirectCloneKeyMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    ResultCode             `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3,enum=consistent_hash.ResultCode" json:"result_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectCloneKeyMessageResponse) Reset() {
	*x = RedirectCloneKeyMessageResponse{}
	mi := &file_proto_consistent_hash_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectCloneKeyMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectCloneKeyMessageResponse) ProtoMessage() {}

func (x *RedirectCloneKeyMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectCloneKeyMessageResponse.ProtoReflect.Descriptor instead.
func (*RedirectCloneKeyMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{11}
}

func (x *RedirectCloneKeyMessageResponse) GetResultCode() ResultCode {
	if x != nil {
		return x.ResultCode
	}
	return ResultCode_SUCCESS
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_consistent_hash_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consistent_hash_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_consistent_hash_proto_rawDescGZIP(), []int{12}
}

var File_proto_consistent_hash_proto protoreflect.FileDescriptor

const file_proto_consistent_hash_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/consistent_hash.proto\x12\x0fconsistent_hash\"#\n" +
	"\x0fGetValueRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"f\n" +
	"\x10GetValueResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12<\n" +
	"\vresult_code\x18\x02 \x01(\x0e2\x1b.consistent_hash.ResultCodeR\n" +
	"resultCode\"6\n" +
	"\fSetKVRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"M\n" +
	"\rSetKVResponse\x12<\n" +
	"\vresult_code\x18\x01 \x01(\x0e2\x1b.consistent_hash.ResultCodeR\n" +
	"resultCode\"$\n" +
	"\x10DeleteKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"Q\n" +
	"\x11DeleteKeyResponse\x12<\n" +
	"\vresult_code\x18\x01 \x01(\x0e2\x1b.consistent_hash.ResultCodeR\n" +
	"resultCode\"\xab\x01\n" +
	"\rServiceRecord\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12-\n" +
	"\x12hearbeat_timestamp\x18\x03 \x01(\x04R\x11hearbeatTimestamp\x12\x14\n" +
	"\x05vnode\x18\x04 \x03(\tR\x05vnode\x12\x1e\n" +
	"\vis_slave_of\x18\x05 \x01(\tR\tisSlaveOf\"O\n" +
	"\x06Gossip\x12E\n" +
	"\x0eservice_record\x18\x01 \x03(\v2\x1e.consistent_hash.ServiceRecordR\rserviceRecord\"l\n" +
	"\x1cRedirectGossipMessageRequest\x12/\n" +
	"\x06gossip\x18\x01 \x01(\v2\x17.consistent_hash.GossipR\x06gossip\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"]\n" +
	"\x1dRedirectGossipMessageResponse\x12<\n" +
	"\vresult_code\x18\x01 \x01(\x0e2\x1b.consistent_hash.ResultCodeR\n" +
	"resultCode\"e\n" +
	"\x1eRedirectCloneKeyMessageRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\"_\n" +
	"\x1fRedirectCloneKeyMessageResponse\x12<\n" +
	"\vresult_code\x18\x01 \x01(\x0e2\x1b.consistent_hash.ResultCodeR\n" +
	"resultCode\"\a\n" +
	"\x05Empty*,\n" +
	"\n" +
	"ResultCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x11\n" +
	"\rKEY_NOT_EXIST\x10\x012\xc5\x02\n" +
	"\x14ConsistentHashServer\x12O\n" +
	"\bGetValue\x12 .consistent_hash.GetValueRequest\x1a!.consistent_hash.GetValueResponse\x12F\n" +
	"\x05SetKV\x12\x1d.consistent_hash.SetKVRequest\x1a\x1e.consistent_hash.SetKVResponse\x12R\n" +
	"\tDeleteKey\x12!.consistent_hash.DeleteKeyRequest\x1a\".consistent_hash.DeleteKeyResponse\x12@\n" +
	"\fListenGossip\x12\x17.consistent_hash.Gossip\x1a\x17.consistent_hash.Gossip2\xb8\x03\n" +
	"\fProxyService\x12O\n" +
	"\bGetValue\x12 .consistent_hash.GetValueRequest\x1a!.consistent_hash.GetValueResponse\x12F\n" +
	"\x05SetKV\x12\x1d.consistent_hash.SetKVRequest\x1a\x1e.consistent_hash.SetKVResponse\x12R\n" +
	"\tDeleteKey\x12!.consistent_hash.DeleteKeyRequest\x1a\".consistent_hash.DeleteKeyResponse\x12v\n" +
	"\x15RedirectGossipMessage\x12-.consistent_hash.RedirectGossipMessageRequest\x1a..consistent_hash.RedirectGossipMessageResponse\x12C\n" +
	"\x10GetAllServerInfo\x12\x16.consistent_hash.Empty\x1a\x17.consistent_hash.GossipB'Z%consistent_hash/proto;consistent_hashb\x06proto3"

var (
	file_proto_consistent_hash_proto_rawDescOnce sync.Once
	file_proto_consistent_hash_proto_rawDescData []byte
)

func file_proto_consistent_hash_proto_rawDescGZIP() []byte {
	file_proto_consistent_hash_proto_rawDescOnce.Do(func() {
		file_proto_consistent_hash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consistent_hash_proto_rawDesc), len(file_proto_consistent_hash_proto_rawDesc)))
	})
	return file_proto_consistent_hash_proto_rawDescData
}

var file_proto_consistent_hash_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_consistent_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_consistent_hash_proto_goTypes = []any{
	(ResultCode)(0),                         // 0: consistent_hash.ResultCode
	(*GetValueRequest)(nil),                 // 1: consistent_hash.GetValueRequest
	(*GetValueResponse)(nil),                // 2: consistent_hash.GetValueResponse
	(*SetKVRequest)(nil),                    // 3: consistent_hash.SetKVRequest
	(*SetKVResponse)(nil),                   // 4: consistent_hash.SetKVResponse
	(*DeleteKeyRequest)(nil),                // 5: consistent_hash.DeleteKeyRequest
	(*DeleteKeyResponse)(nil),               // 6: consistent_hash.DeleteKeyResponse
	(*ServiceRecord)(nil),                   // 7: consistent_hash.ServiceRecord
	(*Gossip)(nil),                          // 8: consistent_hash.Gossip
	(*RedirectGossipMessageRequest)(nil),    // 9: consistent_hash.RedirectGossipMessageRequest
	(*RedirectGossipMessageResponse)(nil),   // 10: consistent_hash.RedirectGossipMessageResponse
	(*RedirectCloneKeyMessageRequest)(nil),  // 11: consistent_hash.RedirectCloneKeyMessageRequest
	(*RedirectCloneKeyMessageResponse)(nil), // 12: consistent_hash.RedirectCloneKeyMessageResponse
	(*Empty)(nil),                           // 13: consistent_hash.Empty
}
var file_proto_consistent_hash_proto_depIdxs = []int32{
	0,  // 0: consistent_hash.GetValueResponse.result_code:type_name -> consistent_hash.ResultCode
	0,  // 1: consistent_hash.SetKVResponse.result_code:type_name -> consistent_hash.ResultCode
	0,  // 2: consistent_hash.DeleteKeyResponse.result_code:type_name -> consistent_hash.ResultCode
	7,  // 3: consistent_hash.Gossip.service_record:type_name -> consistent_hash.ServiceRecord
	8,  // 4: consistent_hash.RedirectGossipMessageRequest.gossip:type_name -> consistent_hash.Gossip
	0,  // 5: consistent_hash.RedirectGossipMessageResponse.result_code:type_name -> consistent_hash.ResultCode
	0,  // 6: consistent_hash.RedirectCloneKeyMessageResponse.result_code:type_name -> consistent_hash.ResultCode
	1,  // 7: consistent_hash.ConsistentHashServer.GetValue:input_type -> consistent_hash.GetValueRequest
	3,  // 8: consistent_hash.ConsistentHashServer.SetKV:input_type -> consistent_hash.SetKVRequest
	5,  // 9: consistent_hash.ConsistentHashServer.DeleteKey:input_type -> consistent_hash.DeleteKeyRequest
	8,  // 10: consistent_hash.ConsistentHashServer.ListenGossip:input_type -> consistent_hash.Gossip
	1,  // 11: consistent_hash.ProxyService.GetValue:input_type -> consistent_hash.GetValueRequest
	3,  // 12: consistent_hash.ProxyService.SetKV:input_type -> consistent_hash.SetKVRequest
	5,  // 13: consistent_hash.ProxyService.DeleteKey:input_type -> consistent_hash.DeleteKeyRequest
	9,  // 14: consistent_hash.ProxyService.RedirectGossipMessage:input_type -> consistent_hash.RedirectGossipMessageRequest
	13, // 15: consistent_hash.ProxyService.GetAllServerInfo:input_type -> consistent_hash.Empty
	2,  // 16: consistent_hash.ConsistentHashServer.GetValue:output_type -> consistent_hash.GetValueResponse
	4,  // 17: consistent_hash.ConsistentHashServer.SetKV:output_type -> consistent_hash.SetKVResponse
	6,  // 18: consistent_hash.ConsistentHashServer.DeleteKey:output_type -> consistent_hash.DeleteKeyResponse
	8,  // 19: consistent_hash.ConsistentHashServer.ListenGossip:output_type -> consistent_hash.Gossip
	2,  // 20: consistent_hash.ProxyService.GetValue:output_type -> consistent_hash.GetValueResponse
	4,  // 21: consistent_hash.ProxyService.SetKV:output_type -> consistent_hash.SetKVResponse
	6,  // 22: consistent_hash.ProxyService.DeleteKey:output_type -> consistent_hash.DeleteKeyResponse
	10, // 23: consistent_hash.ProxyService.RedirectGossipMessage:output_type -> consistent_hash.RedirectGossipMessageResponse
	8,  // 24: consistent_hash.ProxyService.GetAllServerInfo:output_type -> consistent_hash.Gossip
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_consistent_hash_proto_init() }
func file_proto_consistent_hash_proto_init() {
	if File_proto_consistent_hash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consistent_hash_proto_rawDesc), len(file_proto_consistent_hash_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_consistent_hash_proto_goTypes,
		DependencyIndexes: file_proto_consistent_hash_proto_depIdxs,
		EnumInfos:         file_proto_consistent_hash_proto_enumTypes,
		MessageInfos:      file_proto_consistent_hash_proto_msgTypes,
	}.Build()
	File_proto_consistent_hash_proto = out.File
	file_proto_consistent_hash_proto_goTypes = nil
	file_proto_consistent_hash_proto_depIdxs = nil
}
