// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: consistent_hash.proto

package proxyservice

import (
	"context"

	"consistent_hash/consistent_hash/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteKeyRequest                = proto_consistent_hash.DeleteKeyRequest
	DeleteKeyResponse               = proto_consistent_hash.DeleteKeyResponse
	Empty                           = proto_consistent_hash.Empty
	GetValueRequest                 = proto_consistent_hash.GetValueRequest
	GetValueResponse                = proto_consistent_hash.GetValueResponse
	Gossip                          = proto_consistent_hash.Gossip
	RedirectCloneKeyMessageRequest  = proto_consistent_hash.RedirectCloneKeyMessageRequest
	RedirectCloneKeyMessageResponse = proto_consistent_hash.RedirectCloneKeyMessageResponse
	RedirectGossipMessageRequest    = proto_consistent_hash.RedirectGossipMessageRequest
	RedirectGossipMessageResponse   = proto_consistent_hash.RedirectGossipMessageResponse
	ServiceRecord                   = proto_consistent_hash.ServiceRecord
	SetKVRequest                    = proto_consistent_hash.SetKVRequest
	SetKVResponse                   = proto_consistent_hash.SetKVResponse

	ProxyService interface {
		// those three apis are for client usage
		GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
		SetKV(ctx context.Context, in *SetKVRequest, opts ...grpc.CallOption) (*SetKVResponse, error)
		DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error)
		// redirect all kinds of message
		RedirectGossipMessage(ctx context.Context, in *RedirectGossipMessageRequest, opts ...grpc.CallOption) (*RedirectGossipMessageResponse, error)
		GetAllServerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Gossip, error)
	}

	defaultProxyService struct {
		cli zrpc.Client
	}
)

func NewProxyService(cli zrpc.Client) ProxyService {
	return &defaultProxyService{
		cli: cli,
	}
}

// those three apis are for client usage
func (m *defaultProxyService) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	client := proto_consistent_hash.NewProxyServiceClient(m.cli.Conn())
	return client.GetValue(ctx, in, opts...)
}

func (m *defaultProxyService) SetKV(ctx context.Context, in *SetKVRequest, opts ...grpc.CallOption) (*SetKVResponse, error) {
	client := proto_consistent_hash.NewProxyServiceClient(m.cli.Conn())
	return client.SetKV(ctx, in, opts...)
}

func (m *defaultProxyService) DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error) {
	client := proto_consistent_hash.NewProxyServiceClient(m.cli.Conn())
	return client.DeleteKey(ctx, in, opts...)
}

// redirect all kinds of message
func (m *defaultProxyService) RedirectGossipMessage(ctx context.Context, in *RedirectGossipMessageRequest, opts ...grpc.CallOption) (*RedirectGossipMessageResponse, error) {
	client := proto_consistent_hash.NewProxyServiceClient(m.cli.Conn())
	return client.RedirectGossipMessage(ctx, in, opts...)
}

func (m *defaultProxyService) GetAllServerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Gossip, error) {
	client := proto_consistent_hash.NewProxyServiceClient(m.cli.Conn())
	return client.GetAllServerInfo(ctx, in, opts...)
}
